# Generated by Django 5.2.13 on 2026-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='upload_progress',
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
