# Generated by Django 5.2.13 on 2026-04-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('Mentor', 'mentor'), ('Student', 'student')], max_length=15),
        ),
    ]
